### ISSUE TITLE
DetailsPage-ზე quantity-ს ცვლილება ფასზე არ აისახება

### ISSUE THREAD

**Issue by Nato-tsrs** [kunaia/kiushop-front#30]

**Comment by kunaia** [comment]
ხო ეგ ცოტა სხვანაირად უნდა გავაკეთოთ. @mateiahacks ეგ quantity ვაფშე ამოვაგდოთ მაქედან და როგორც ქარდებიდან ხდება დაჭერისას ერთი ცალი რო ემატება კალათში ეგრე გავაკეთოთ
