### ISSUE TITLE
ცვლილება პროდუქტის დეტალებში

### ISSUE THREAD

**Issue by kunaia** [kunaia/kiushop-front#32]
![Screenshot from 2022-08-04 14-52-51](https://user-images.githubusercontent.com/45307416/182830801-ea96dec2-58d5-4889-83d5-7941322a9564.png)

1. ვალუტა ავიტანოთ ფასის გვერდზე
2. ინფორმაციებს ბორდერები არ ჭირდება. მართკუთხედ უჯრებში როა ჩასმული რაღაც ულამაზოდ ჩანს
3. quantity არ გვინდა, და ჩავანაცვლოთ "amount in stock"-ით
4. "add to cart" ღილაკზე დაჭერისას პოსტ მოთხოვნა გააგზავნე ბექზე, და ყოველ დაჭერაზე ერთი ცალი დაემატება კალათაში

**Comment by kunaia** [comment]
ბოლო პუნქტი არაა შესრულებული

**Comment by mateiahacks** [comment]
გავაკეთე და ძველებურად მთლიან ბასკეთს აღარ ატან მარტო ბასკეთ თაითლს ატან არადა მჭირდება

**Comment by kunaia** [comment]
პოსტ-ის დროს არ მოგდის?
