### ISSUE TITLE
პროდუქტის მარაგის ცვლილება (amount)

### ISSUE THREAD

**Issue by kunaia** [kunaia/kiushop-front#36]
პროდუქტის ედითში გვქონდა ეს ჩაშენებული და უნდა გავაცალკევოთ.

მარაგის განახლებას გააკეთებ `[PUT] /product/4/amount?amount=<amount_to_add>` მოთხოვნა და მიაბა ტოკენი. აქ შეგიძლია დადებითი ან უარყოფითი რიცხვი გაატანო. ორივე ვარიანტში გატნეული რიცხვი დაემატება მარაგს. (ანუ უარყოფითი რიცხვის გამოყენება შეგიძლია მარაგის შესამცირებლად)

**Comment by mateiahacks** [comment]
გავაკეთე ოღონდ +1 და -1 როგორც თქვი
